In [1]:
# This notebook is for testing functions before using in final report

# Imports

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
import sklearn.preprocessing as p
from sklearn.model_selection import train_test_split

import wrangle as w
import explore as e
import acquire as a
import warnings
warnings.filterwarnings("ignore")
import env

%matplotlib inline
# %config InlineBackend.figure_format = 'svg'

In [2]:
train, validate, test = w.wrangle_zillow()

In [4]:
e.county_dummies(train)

,parcel_id,property_id,bathrooms,bedrooms,zip_code,year_built,total_sqft,tax_value
31793,11121796,1061586,3.0,4,96373,1978,2322,428575.0
52132,11242608,685818,3.0,4,97298,2007,3537,647000.0
36759,13083122,338261,2.0,4,96488,1964,1326,245335.0
27845,10999046,2433183,3.0,4,96282,1937,1774,389856.0
10940,14275253,146283,2.0,4,96981,1953,1795,571678.0
...,...,...,...,...,...,...,...,...
36610,12419984,923630,3.0,4,96204,2003,2575,692000.0
37446,10925192,464450,2.0,3,96437,1944,1228,408327.0
28826,11011304,2388453,3.0,4,96368,2000,2599,528945.0
7133,14252386,2040261,3.0,5,97006,1938,2866,440273.0
25682,14100506,593082,2.5,3,96185,1974,1799,78282.0